# Variables globales pour la configuration Ansible
# =============================================

# Configuration de base
global:
  environment: production
  project_name: "ForFun IaC Basic"
  deployment_date: "{{ ansible_date_time.iso8601 }}"

# Configuration SSH
ssh:
  host_key_checking: False
  timeout: 30
  retries: 3

# Configuration de l'inventaire
inventory:
  path: ./inventory.ini

# Configuration générale
general:
  retry_files_enabled: False
  interpreter_python: auto

# Configuration des tâches conditionnelles
tasks:
  update_cache: true
  install_packages: true
  deploy_content: true
  start_services: true

# Configuration des conditions
conditions:
  os_family: "Debian"
  package_manager: "apt"

# Configuration des paquets
packages:
  update_cache: yes
  install:
    - nginx
  state: present

# Configuration du service
service:
  name: nginx
  state: started
  enabled: yes

# Configuration des fichiers
files:
  template:
    src: templates/index.html.j2
    dest: /var/www/html/index.html
    mode: '0644'

# Configuration Nginx
nginx:
  config_dir: /etc/nginx
  sites_available: /etc/nginx/sites-available
  sites_enabled: /etc/nginx/sites-enabled
  log_dir: /var/log/nginx
  document_root: /var/www/html
  port: 80
  ssl_port: 443

# Configuration des performances
performance:
  worker_processes: auto
  worker_connections: 1024
  keepalive_timeout: 65
  client_max_body_size: 10M

# Configuration de sécurité
security:
  firewall_enabled: false
  ufw_policy: deny
  allowed_ports:
    - 22
    - 80
    - 443
  ssl_enabled: false
  basic_auth_enabled: false

# Configuration de monitoring
monitoring:
  enabled: false
  health_check_path: /health
  metrics_port: 9100
  log_rotation: true
  log_retention_days: 30

# Variables d'environnement
environment:
  node_env: production
  debug: false
  log_level: info
  cache_enabled: true
  compression_enabled: true 