- name: Configure web server with Nginx
  hosts: web
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install Nginx
      apt:
        name: nginx
        state: present
      when: ansible_os_family == "Debian"

    - name: Create web directory if not exists
      file:
        path: /var/www/html
        state: directory
        mode: '0755'
        owner: www-data
        group: www-data

    - name: Deploy custom index.html
      template:
        src: templates/index.html.j2
        dest: /var/www/html/index.html
        mode: '0644'
        owner: www-data
        group: www-data

    - name: Ensure nginx running and enabled
      service:
        name: nginx
        state: started
        enabled: yes
